### ISSUE TITLE
Adding users - multiple with roles 

### ISSUE THREAD

**Issue by beth-german** [pulibrary/aux#4]
### User story

Add multiple users with assigned roles to Data Users 
* Select netid from set list of netids available in the system 
* Only allow users to select netids from the list and give information about why it failed 
* Clearly see who has what level of access and be able to change it 
* Remove someone from the list of data users 

### Acceptance criteria

- [ ] If this change touches any of the files referenced in `.rubocop_todo.yml` create a new ticket to address the rubocop  todo.
- [ ] I can successfully use this feature with Voice Over in Safari.
- [ ] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave
- [ ] ...

### Concrete example

Current state
![image](https://github.com/user-attachments/assets/8cac34f1-ff66-45c5-aba5-15ceac490163)

Midlevel mockup
![image](https://github.com/user-attachments/assets/3c82cd32-b248-4ec4-8f01-573028e763e0)

**Comment by beth-german** [comment]
Data user ticket: https://github.com/pulibrary/tigerdata-app/issues/248

**Comment by gnemade51** [comment]
**Multiple Select Users:**

This flow has 5 variations that we have thought of. @matthewjchandler and @beth-german  could you review these and we can break and make the final iteration of this flow.

(The images may be small due to the layout size. Better viewed in Figma)

variation 1
![image](https://github.com/user-attachments/assets/4aab8ed8-f2db-43ab-983b-243181d2015d)

variation 2
![image](https://github.com/user-attachments/assets/bb72f604-8c21-4b4a-b49d-8bbe73b24c58)

variation 3:
![image](https://github.com/user-attachments/assets/42feb4bc-176a-4a31-b074-cf9229017ffb)

variation 4:
![image](https://github.com/user-attachments/assets/4c325dd8-cd25-4358-bb79-74c2ef0367a8)

variation 5:
![image](https://github.com/user-attachments/assets/cfb2ebd2-a811-4814-9c27-b15e94e780c4)


Figma Link:
https://www.figma.com/proto/rgzEYTpnGl6l68moRSVwYg/Phase-1-UI-Details?page-id=0%3A1&node-id=90-1004&node-type=frame&viewport=-21%2C-1177%2C0.22&t=7oBPcTUMBjWSwLMx-1&scaling=contain&content-scaling=fixed

**Comment by cass1ex** [comment]
**Latest Update**

Final version (confirmed with Beth and Kate for design & technical feasibility) of adding single/multiple users for Data User. 

This version uses a table with 2 button actions below, when user clicks on "Add User(s)", a modal pops up for user to select or type in netids, then the selected users will be added as individual rows in the table. By default all the users have "read only" permission.

To edit, click the "edit" button and user can change permission to "read/write" if needed or remove any data user. 

![Image](https://github.com/user-attachments/assets/e2259dc6-66e0-4b98-8dca-c7ae2cf607f5)

See Figma dev mode for more alignment details:

![Image](https://github.com/user-attachments/assets/1cbe61ba-cde9-45ce-990f-bec8f79ce815)
![Image](https://github.com/user-attachments/assets/b44922a5-5c5b-407d-9d74-3a7af1568e0a)

Link to Figma: https://www.figma.com/design/rgzEYTpnGl6l68moRSVwYg/Phase-1-UI-Details?node-id=246-1473&m=dev

**Comment by beth-german** [comment]
Continued in: https://github.com/pulibrary/tigerdata-app/issues/984
